name: Build and Push Python Docker Image

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      # Required for building multi-platform images
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      # Builds images more efficiently with caching and multi-platform support
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      # Authenticates with Docker Hub using your secrets
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Replace with your Docker Hub username

    - name: Build and push Docker image
      # The main action to build and push the image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/face-analysis:latest
        # Replace with your Docker Hub username and image name
